default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: inhumane_cards_development

test:
  <<: *default
  database: inhumane_cards_test

production:
  <<: *default
  database: inhumane_cards_production
  username: inhumane_cards
  password: <% ENV["INHUMANE_CARDS_DATABASE_PASSWORD"] %>